version: '3.8'

services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=demo
    ports:
      - "5432:5432"